name: xskt_app
description: Ứng dụng phân tích và tạo bảng cược xổ số kiến thiết
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Thêm dòng này
  flutter_launcher_icons: ^0.13.1

  shimmer: ^3.0.0
  fl_chart: ^0.66.0
  
  # State Management
  provider: ^6.1.1

  dio: ^5.3.0
  cookie_jar: ^4.0.0
  dio_cookie_manager: ^3.0.0

  # Google Sheets API
  googleapis_auth: ^1.4.1
  xml: ^6.3.0

  # WebView
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.0  # ✅ Thêm
  webview_flutter_wkwebview: ^3.9.4
  webview_flutter_web: ^0.2.0

  # Local Storage
  shared_preferences: ^2.2.2

  # UI Components
  flutter_screenutil: ^5.9.0
  data_table_2: ^2.5.9

  # Utilities
  intl: ^0.18.1

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true                 # Kích hoạt cho Android
  ios: true                     # Kích hoạt cho iOS
  image_path: "icon.png" # Đường dẫn đến file icon của bạn
  min_sdk_android: 21           # (Tùy chọn) Yêu cầu Android API 21+

flutter_native_splash:
  # Đây chính là file ảnh gây ra lỗi
  image: icon.png 
  android: true
  ios: true

  # Assets (nếu cần)
  # assets:
  #   - images/
  #   - icons/

  # Fonts (nếu cần)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700